services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=nflfantasydraftinventory'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5430:5432'